@InterviewPrepAPI_HostAddress = https://localhost:7183
@InterviewPrepAPI_HttpAddress = http://localhost:5197

### Get OpenAPI spec
GET {{InterviewPrepAPI_HttpAddress}}/openapi/v1.json
Accept: application/json

###
